# Wanna look for more?
# Check this catppuccin wallpapers https://github.com/zhichaoh/catppuccin-wallpapers
preload = ~/.config/hypr/wallpaper/fixi.jpg

wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpaper/fixi.jpg
    fit_mode = cover
}

ipc = on
